config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  resources :static_pages, only: [:index]
  devise_for :users
  resources :posts do
    resources :replies, only: [:create, :new, :destroy, :edit, :update]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true
  belongs_to :user
  has_many :replies

  def self.search(search)
    if search
      Post.where('title ILIKE ?', "%#{search}%")
    else
      Post.all
    end
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  validates :user, presence: true
  validates :post, presence: true
  validates :body, presence: true
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :avatar, presence: true
  mount_uploader :avatar, AvatarUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :replies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password,
      :password_confirmation, :current_password, :avatar, :avatar_cache) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :authenticate_user!, except: [:home]
   before_action :authorize_user, only: [:new, :create, :destroy, :edit]

  def index
    @posts = Post.search(params[:search]).order(created_at: :desc).limit(10).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @reply = Reply.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash[:notice] = 'Success'
      redirect_to posts_path
    else
      render :new
    end
  end

  def destroy
    if current_user
      @post = Post.find(params[:id])
      if @post.destroy
        flash[:notice] = 'Post deleted!'
        redirect_to posts_path
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
    verify_authorized!(@post)
  end

  def update
    @post = Post.find(params[:id])
    verify_authorized!(@post)
    if @post.update(post_params)
      redirect_to(@post)
    else
      flash.now[:notice] = 'Much Fail, Very Sad, Edit Failed'
      render :edit
    end
  end

 private

  def verify_authorized!(post)
    if current_user != post.user
      flash[:notice] = 'You did not make this post! Random Shibe.'
      redirect_to post_path
    end
  end

  def authorize_user
    unless user_signed_in? and current_user
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def post_params
    params.require(:post).permit(:title, :body, :uid)
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authorize_user, only: [:new, :create, :destroy, :edit]
 def create
    @post = Post.find(params[:post_id])
    @reply = @post.replies.build(reply_params)
    @reply.user = current_user
    @user = @reply.user

    if @reply.save
      flash[:notice] = 'Your reply was saved!'
      redirect_to post_path(@post)
    else
      @post.replies.delete(@reply)
      flash[:notice] = 'Your reply could not be saved'
      render 'posts/show'
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @reply = Reply.find(params[:id])
    if @reply.destroy
      flash[:notice] = 'Reply deleted!'
      redirect_to post_path(@post)
    end
  end

  def update
    @post = Post.find(params[:post_id])
    @reply = Reply.find(params[:id])
    if @reply.update(reply_params)
      flash[:notice] = 'Changes saved!'
      redirect_to post_path(@post)
    end
  end

  private

  def authorize_user
    unless user_signed_in? and current_user
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def reply_params
    params.require(:reply).permit(:body)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    controller = params[:controller].gsub(/(_|\/)/, '-')
    action = "#{controller}-#{params[:action]}"

    [controller, action].join(' ')
  end

  def flash_class(level)
    case level
      when :notice then "alert alert-info"
      when :success then "alert alert-success"
      when :error then "alert alert-error"
      when :alert then "alert alert-error"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doge Nation</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">
  <header class="page-header">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
             <% if user_signed_in? %>
            <li><%= link_to 'Such Home', static_pages_path, method: :get %></li>
            <li><%= link_to 'Very Posts', posts_path, method: :get %></li>
            <li><%= link_to 'Much New Posts', new_post_path, method: :get %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to 'Such Home', static_pages_path, method: :get %></li>
            <li><%= link_to 'So Login', new_user_session_path, method: :get %></li>
            <li><%= link_to 'Much Sign Up', new_user_registration_path, method: :get %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </header>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |key, value| %>
          <div class="<%= flash_class(key) %>">
            <%= value %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<%= yield %>
</body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>:
  <%= f.text_field :title %><br>

  <%= f.label :body %>:
  <%= f.text_area :body %><br>

  <%= f.submit 'So Save', class: "btn btn-warning" %>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
      <div class="col-lg-12">
        <%= form_tag(posts_path, method: "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search For Posts" %>
          <%= submit_tag "Much Search", class: "btn btn-danger" %>
        <% end %>
      </div>
  </div>
</div>
<table class="table table-hover">
  <thead>
    <tr class="table_header">
      <th>Recent Shibes Barking</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |p| %>
      <tr>
        <td style="width:100%"><%= link_to p.title, post_path(p) %> <%= p.created_at.strftime("%b %d, %Y")%> <%= p.user.email %></td>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
<%= paginate @posts %>
<div class="row">
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <img src="https://s3.amazonaws.com/doges/harry_doge.jpg" class="thumbnail img-responsive">
  </div>
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <img src="https://s3.amazonaws.com/doges/flat_doge.png" class="thumbnail img-responsive">
  </div>
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <img src="https://s3.amazonaws.com/doges/roman_doge.png" class="thumbnail img-responsive">
  </div>
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <img src="https://s3.amazonaws.com/doges/windoge.jpg" class="thumbnail img-responsive">
  </div>
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <img src="https://s3.amazonaws.com/doges/nature_doge.jpg" class="thumbnail img-responsive">
  </div>
  <div class="col-lg-4 col-sm-6 col-xs-12">
    <img src="https://s3.amazonaws.com/doges/talentdoge.jpg" class="thumbnail img-responsive">
  </div>
</div>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
<div class="container">
  <div class="row">
      <div class="col-md-6 col-md-offset-4">
        <div class="well well-sm">
          <fieldset>
            <legend class="text-center">Much New Post</legend>
            <div class="form-group">
              <label class="col-md-3 control-label" for="title"><%= f.label :title %>:</label>
              <div class="col-md-9">
                <%= f.text_field :title, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label" for="body"><%= f.label :body %>:</label>
              <div class="col-md-9">
                <%= f.text_area :body, class: "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-md-12 text-right">
                <%= f.submit 'Submit', class: "btn btn-warning" %>
              </div>
            </div>
          </fieldset>
        </div>
      </div>
  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="span4 well" style="padding-bottom:0">
      <%= @post.title %><br>
      <%= @post.body %><br>
      <%= @post.user.email %>
      <% if current_user == @post.user %>
      <%= button_to 'So Delete', "/posts/#{@post.id}",
              method: :delete, data:
              { confirm: 'Much Shibe, Very Warn, Sure you want to delete?' },
              id: "delete-post-#{@post.id}", class: "btn btn-danger" %>
      <%= button_to 'Much Edit', edit_post_path(@post),
          method: :get, id: "edit-post-#{@post.id}", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>
</div>
<% @post.replies.each do |reply| %>
  <ul>
     <div class="container">
        <div class="row">
          <div class="span4 well" style="padding-bottom:0">
            <li><%= reply.body %> By: <%= image_tag(reply.user.avatar.url, size: "80x80") %><%= reply.user.email%></li>
              <% if reply.user == current_user %>
                <%= button_to 'So Delete', post_reply_path(@post, reply),
                    method: :delete, data:
                    { confirm: 'Much Shibe, Very Warn, Sure you want to delete?' },
                    id: "delete-reply-#{reply.id}", class: "btn btn-danger" %>
                  <% if reply.errors.any? %>
                    <p>There were errors with your submission:</p>
                      <ul>
                      <% review.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                  <% end %>
                      </ul>
              <% end %>
            </div>
          </div>
        </div>
        <div class="container">
          <div class="row">
            <div class="span4 well" style="padding-bottom:0">
              <%= form_for [@post, reply], html:
                    { id: "editing-reply-#{reply.id}" },
                    url: post_reply_path(@post, reply),
                    method: :patch do |f| %>
              <h5>Edit A Reply</h5>
                <%= f.label :body %>
                <%= f.text_area :body %>
                <%= f.submit "Much Edit Reply", class: "btn btn-warning" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </ul>
<% end %>
<%= form_for [@post, @reply] do |f| %>
  <% if @reply.errors.any? %>
    <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  <% end %>
<div class="container">
  <div class="row">
    <div class="span4 well" style="padding-bottom:0">
      <h5>Add A Reply</h5>
      <form accept-charset="UTF-8" action="" method="POST">
        <%= f.label :body %>
        <%= f.text_area :body %>
        <%= f.submit 'Very Submit', class: "btn btn-primary" %>
      </form>
    </div>
  </div>
</div>
<% end %>

app/views/static_pages/home.html.erb
<link href='http://fonts.googleapis.com/css?family=Buenard:700' rel='stylesheet' type='text/css'>
<script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>
<div class="beep">
  <section class="content-section video-section">
    <div class="pattern-overlay">
    <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=sd4bqmP_460',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
    </div>
  </section>
</div>
<h2 class="cent">Welcome Fellow Shibes!</h2>
<h3 class="cent">You need to sign up/in to learn the secerts of the shibe</h3>

app/views/static_pages/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Buenard:700' rel='stylesheet' type='text/css'>
<script src="http://pupunzi.com/mb.components/mb.YTPlayer/demo/inc/jquery.mb.YTPlayer.js"></script>
<div class="beep">
  <section class="content-section video-section">
    <div class="pattern-overlay">
    <a id="bgndVideo" class="player" data-property="{videoURL:'https://www.youtube.com/watch?v=sd4bqmP_460',containment:'.video-section', quality:'large', autoPlay:true, mute:true, opacity:1}">bg</a>
    </div>
  </section>
</div>
<h2 class="cent">Welcome Fellow Shibes!</h2>
<h3 class="cent">You need to <%= button_to 'Much Sign Up',
      new_user_session_path, method: :get, class: "btn btn-danger" %><%= button_to 'So Login', new_user_session_path, method: :get, class: "btn btn-danger" %>in order to learn the secerts of the shibe</h3>
<br>
<div class="container">
    <div class="row">
        <div id="transition-timer-carousel" class="carousel slide transition-timer-carousel" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#transition-timer-carousel" data-slide-to="0" class="active"></li>
        <li data-target="#transition-timer-carousel" data-slide-to="1"></li>
        <li data-target="#transition-timer-carousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
                    <img src="https://s3.amazonaws.com/doges/dream_doge.jpg"/>
                    <div class="carousel-caption">
                        <h1 class="carousel-caption-header">Follow Your Dreams, Fellow Shibes</h1>
                        <p class="carousel-caption-text hidden-sm hidden-xs">
                            This site is about fellow shibes coming together in a friendly atmoshpere.
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="https://s3.amazonaws.com/doges/doge_stars.jpg" />
                    <div class="carousel-caption">
                        <h1 class="carousel-caption-header">Such Stars</h1>
                        <p class="carousel-caption-text hidden-sm hidden-xs">
                            Dogenation is about getting together and having a shibe ole time!
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="https://s3.amazonaws.com/doges/moon_doge.png" />
                    <div class="carousel-caption">
                        <h1 class="carousel-caption-header">Shibe Uniqueness!</h1>
                        <p class="carousel-caption-text hidden-sm hidden-xs">
                            Show each other the greatness that is doge!
                        </p>
                    </div>
                </div>
            </div>
      <a class="left carousel-control" href="#transition-timer-carousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </a>
      <a class="right carousel-control" href="#transition-timer-carousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
            <hr class="transition-timer-carousel-progress-bar animate" />
    </div>
    </div>
</div>